FROM node:20-alpine

WORKDIR /app

# Sadece paket listesini kopyalayıp kur
COPY package.json package-lock.json* ./
RUN npm install

# Kodu kopyala
COPY . .

# Dev server'ı başlat
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
